/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PiperReader
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  piperBinaryPath: "/home/mcrispen/.local/share/piper/piper",
  modelPath: "/home/mcrispen/.local/share/piper/models/en_US-lessac-medium.onnx",
  outputTempPath: "/tmp",
  defaultModel: "en_US-lessac-medium"
};

// src/piper.ts
var import_child_process = require("child_process");
var import_promises = require("fs/promises");
var import_path = require("path");
var import_os = require("os");
var PiperIntegration = class {
  constructor(binaryPath, modelPath, tempPath) {
    this.binaryPath = binaryPath;
    this.modelPath = modelPath;
    this.tempPath = tempPath || (0, import_os.tmpdir)();
  }
  async synthesizeSpeech(text) {
    if (!this.binaryPath || !this.modelPath) {
      throw new Error("Piper binary path and model path must be configured");
    }
    const sanitizedText = this.sanitizeText(text);
    const timestamp = Date.now();
    const random = Math.floor(Math.random() * 1e3);
    const outputFileName = `piper-${timestamp}-${random}.wav`;
    const outputPath = (0, import_path.join)(this.tempPath, outputFileName);
    try {
      const result = await this.runPiper(sanitizedText, outputPath);
      if (result.success) {
        return outputPath;
      } else {
        throw new Error(`Piper synthesis failed: ${result.error}`);
      }
    } catch (error) {
      try {
        await (0, import_promises.unlink)(outputPath);
      } catch (cleanupError) {
      }
      throw error;
    }
  }
  async runPiper(text, outputPath) {
    return new Promise((resolve) => {
      var _a, _b;
      const env = { ...global.process.env };
      env.LD_LIBRARY_PATH = `/home/mcrispen/.local/share/piper:${global.process.env.LD_LIBRARY_PATH || ""}`;
      const args = [
        "-m",
        this.modelPath,
        "-f",
        outputPath,
        "--espeak_data",
        "/home/mcrispen/.local/share/piper/espeak-ng-data"
      ];
      const piperProcess = (0, import_child_process.spawn)(this.binaryPath, args, { env });
      let stderr = "";
      let stdout = "";
      (_a = piperProcess.stderr) == null ? void 0 : _a.on("data", (data) => {
        stderr += data.toString();
      });
      (_b = piperProcess.stdout) == null ? void 0 : _b.on("data", (data) => {
        stdout += data.toString();
      });
      piperProcess.on("error", (error) => {
        resolve({ success: false, error: error.message });
      });
      piperProcess.on("close", (code) => {
        if (code === 0) {
          resolve({ success: true });
        } else {
          resolve({
            success: false,
            error: `Piper exited with code ${code}. Stderr: ${stderr}`
          });
        }
      });
      if (piperProcess.stdin) {
        piperProcess.stdin.write(text);
        piperProcess.stdin.end();
      }
    });
  }
  sanitizeText(text) {
    return text.replace(/\[([^\]]+)\]/g, "").replace(/```[\s\S]*?```/g, "").replace(/`([^`]+)`/g, "$1").replace(/#{1,6}\s+/g, "").replace(/\*\*([^*]+)\*\*/g, "$1").replace(/\*([^*]+)\*/g, "$1").replace(/!\[([^\]]*)\]\([^)]+\)/g, "").replace(/\[([^\]]+)\]\([^)]+\)/g, "$1").replace(/^\s*[-*+]\s+/gm, "").replace(/^\s*\d+\.\s+/gm, "").replace(/\n{3,}/g, "\n\n").trim();
  }
  async cleanupTempFile(filePath) {
    try {
      await (0, import_promises.unlink)(filePath);
    } catch (error) {
    }
  }
};

// src/audio.ts
var import_promises2 = require("fs/promises");
var AudioPlayer = class {
  constructor() {
    this.currentAudio = null;
    this.currentFilePath = null;
    this.currentBlobUrl = null;
    this.audioEndedEvent = null;
  }
  async playAudio(filePath) {
    this.stop();
    try {
      const buffer = await (0, import_promises2.readFile)(filePath);
      const blob = new Blob([new Uint8Array(buffer)], { type: "audio/wav" });
      const blobUrl = URL.createObjectURL(blob);
      this.currentBlobUrl = blobUrl;
      this.currentAudio = new Audio(blobUrl);
      this.currentFilePath = filePath;
      this.currentAudio.addEventListener("ended", () => {
        if (this.audioEndedEvent) {
          this.audioEndedEvent();
        }
        this.cleanup();
      });
      this.currentAudio.addEventListener("error", (error) => {
        console.error("Audio playback error:", error);
        this.cleanup();
      });
      await this.currentAudio.play();
    } catch (error) {
      this.cleanup();
      throw error;
    }
  }
  stop() {
    if (this.currentAudio) {
      this.currentAudio.pause();
      this.currentAudio.currentTime = 0;
    }
    this.cleanup();
  }
  pause() {
    if (this.currentAudio && !this.currentAudio.paused) {
      this.currentAudio.pause();
    }
  }
  resume() {
    if (this.currentAudio && this.currentAudio.paused) {
      this.currentAudio.play().catch((error) => {
        console.error("Failed to resume audio:", error);
      });
    }
  }
  isPlaying() {
    return this.currentAudio !== null && !this.currentAudio.paused;
  }
  isPaused() {
    return this.currentAudio !== null && this.currentAudio.paused;
  }
  getCurrentTime() {
    var _a;
    return ((_a = this.currentAudio) == null ? void 0 : _a.currentTime) || 0;
  }
  getDuration() {
    var _a;
    return ((_a = this.currentAudio) == null ? void 0 : _a.duration) || 0;
  }
  setCurrentTime(time) {
    if (this.currentAudio) {
      this.currentAudio.currentTime = time;
    }
  }
  cleanup() {
    if (this.currentBlobUrl) {
      URL.revokeObjectURL(this.currentBlobUrl);
      this.currentBlobUrl = null;
    }
    if (this.currentAudio) {
      this.currentAudio = null;
    }
    this.currentFilePath = null;
  }
  getCurrentFilePath() {
    return this.currentFilePath;
  }
};

// src/main.ts
var PiperReader = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.piperIntegration = new PiperIntegration(
      this.settings.piperBinaryPath,
      this.settings.modelPath,
      this.settings.outputTempPath
    );
    this.audioPlayer = new AudioPlayer();
    this.addCommand({
      id: "read-current-note",
      name: "Read current note with Piper",
      callback: () => this.readCurrentNote()
    });
    this.addCommand({
      id: "stop-reading",
      name: "Stop reading",
      callback: () => this.stopReading()
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        menu.addItem((item) => {
          item.setTitle("Read with Piper").setIcon("volume-2").onClick(() => this.readFile(file));
        });
      })
    );
    this.statusBarItem = this.addStatusBarItem();
    this.statusBarItem.setText("\u23F9 Stop reading");
    this.statusBarItem.style.cursor = "pointer";
    this.statusBarItem.style.display = "none";
    this.statusBarItem.addEventListener("click", () => this.stopReading());
    this.addSettingTab(new PiperSettingTab(this.app, this));
  }
  onunload() {
    this.stopReading();
  }
  stopReading() {
    var _a;
    (_a = this.audioPlayer) == null ? void 0 : _a.stop();
    this.statusBarItem.style.display = "none";
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.piperIntegration = new PiperIntegration(
      this.settings.piperBinaryPath,
      this.settings.modelPath,
      this.settings.outputTempPath
    );
  }
  async readCurrentNote() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian.Notice("No active file found");
      return;
    }
    await this.readFile(activeFile);
  }
  async readFile(file) {
    try {
      const content = await this.app.vault.read(file);
      if (!content.trim()) {
        new import_obsidian.Notice("Note is empty");
        return;
      }
      const loadingNotice = new import_obsidian.Notice("Generating speech...", 0);
      try {
        const audioFilePath = await this.piperIntegration.synthesizeSpeech(content);
        loadingNotice.hide();
        this.statusBarItem.style.display = "";
        await this.audioPlayer.playAudio(audioFilePath);
        this.audioPlayer.audioEndedEvent = async () => {
          this.statusBarItem.style.display = "none";
          await this.piperIntegration.cleanupTempFile(audioFilePath);
        };
      } catch (error) {
        loadingNotice.hide();
        this.statusBarItem.style.display = "none";
        throw error;
      }
    } catch (error) {
      console.error("Piper Reader error:", error);
      new import_obsidian.Notice(`Error: ${error.message}`);
    }
  }
};
var PiperSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Crispy's Text to Speech Settings" });
    new import_obsidian.Setting(containerEl).setName("Piper Binary Path").setDesc("Path to the Piper executable (e.g., /usr/local/bin/piper)").addText((text) => text.setPlaceholder("/usr/local/bin/piper").setValue(this.plugin.settings.piperBinaryPath).onChange(async (value) => {
      this.plugin.settings.piperBinaryPath = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Model Path").setDesc("Path to the Piper model file (.onnx)").addText((text) => text.setPlaceholder("/path/to/model.onnx").setValue(this.plugin.settings.modelPath).onChange(async (value) => {
      this.plugin.settings.modelPath = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Output Temp Path").setDesc("Directory for temporary WAV files (leave empty for system temp)").addText((text) => text.setPlaceholder("System temp directory").setValue(this.plugin.settings.outputTempPath).onChange(async (value) => {
      this.plugin.settings.outputTempPath = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Default Model").setDesc("Default Piper model name (for reference)").addText((text) => text.setValue(this.plugin.settings.defaultModel).setDisabled(true));
  }
};
